# fly.toml app configuration file generated for slither-io on 2025-07-14T00:21:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slither-io'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ['app']
  sticky_sessions = true

[[vm]]
  cpus = 8
  memory = '16gb'
  cpu_kind = 'performance'
